name: Cypress Tests

on:
  push:
    branches:
      - main # ajuste conforme o nome de sua branch principal

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Genarate Report
        run: npx allure serve allure-results
